package equacaosegundograu;
/**
 * @author s.igormanoel
 */

import javax.swing.JOptionPane;

public class Equacaosegundograu {
    public static void main(String[] args) {
        int valorA, valorB, valorC, delta, valordeX, xLinha1, xLinha2;
        
        valorA = Integer.parseInt(JOptionPane.showInputDialog("Qual o valor de A?"));
        valorB = Integer.parseInt(JOptionPane.showInputDialog("QUal o valor de B?"));
        valorC = integer.parseInt(JOptionPane.showInputDialog("Qual o valor de C?"))
        
        // terminar o cáculo --> exemplo para teste 5x²-3x-2=0 --> resposta x1 = 1    e   x2 = -0,4
        
        delta =
        valordeX =
        
        xLinha1 = 
        xLinha2 =

            System.out.println("Sua expressão é " + valorA + "x²" + valorB + "x" + valorC + "=0"); 
            System.out.printIn("O valor de X1 é " + xLinha1 + " e o valor de X2 é " + xLinha2);
    }
}